-- ============================================================
-- FILE: 00_migrate_target_tables.sql
-- DESC: DISABLED — target tables are shared with other processes
--       and must not have columns added by this framework.
--
--       Target tables (DIM_STAFFING_SCHEDULE, DIM_STAFFING_TIMELINE,
--       DIM_COST, DIM_TIMELINE_COST) are owned and managed externally.
--       The load packages (PKG_STAFFING_LOAD, PKG_COST_LOAD) write
--       only to columns that already exist in those tables.
--
--       This file is intentionally empty.
-- ============================================================
