-- ============================================================
-- FILE: 01_sequences.sql
-- DESC: All sequences for the EDWH metadata-driven framework
-- SCHEMA: GPC_DM
-- ============================================================

-- Framework infrastructure sequences
CREATE SEQUENCE GPC_DM.SEQ_ETL_RUN_LOG     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_ETL_STEP_LOG    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_ETL_ERROR_LOG   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_ETL_SS          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_ETL_ENTITY      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_ETL_MAPPING     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_ETL_COL_MAP     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_ETL_VAL_RULE    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Target dimension surrogate key sequences
CREATE SEQUENCE GPC_DM.SEQ_DIM_SS          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_DIM_ST          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_DIM_COST        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GPC_DM.SEQ_DIM_TC          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
